# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|

    config.vm.box = "win10"
    config.vm.communicator = "winrm"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

    config.vm.provider :hyperv do |h, override|
        h.cpus = 2
		h.memory = 4096
		h.ip_address_timeout = 240
		h.enable_virtualization_extensions = true
		h.differencing_disk = true
    end
	
	config.vm.provision "shell", path: "ps.ps1", args: "provision-debloat.ps1"
    config.vm.provision "shell", path: "ps.ps1", args: "provision-choco.ps1"
	config.vm.provision "shell", path: "ps.ps1", args: "provision.ps1"
	config.vm.provision "shell", path: "ps.ps1", args: "provision-dotnet-sdk.ps1"
	config.vm.provision :reload
	config.vm.provision "shell", path: "ps.ps1", args: "provision-vs.ps1"
	config.vm.provision "shell", path: "ps.ps1", args: "provision-ssms.ps1"
	config.vm.provision "shell", path: "compact.bat"
end
